### ISSUE TITLE
Disallow non-unit environments in `accept`, `request` etc.

### ISSUE THREAD

**Issue by Munksgaard** [Munksgaard/rust-sessions#4]
I think we should do this. Other implementations do this, and I have yet to see an actual use case. It would also allow us to remove the `HasDualEnv` trait.

**Comment by Munksgaard** [comment]
cc @laumann

**Comment by laumann** [comment]
:+1: Done

**Comment by laumann** [comment]
Sorry, thought you committed the referenced changeset to `master`
